Read all cgroup v2 metrics that can be read
DataDog/lading pull request #1120
Opened 2024-12-03 03:45 UTC by blt

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

2024-12-03 03:46 UTC, blt commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/DataDog/lading/1120?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1120** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1120?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/DataDog/lading/1120?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#1119** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1119?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-03 20:01 UTC, scottopell requested changes

2024-12-03 20:01 UTC, scottopell commented on lading/src/observer/linux.rs
> +            let cgroup_path = v2::get_path(pid).await?;
Can you collect unique cgroups across pids in order to not scrape the same cgroup twice?

2024-12-03 23:07 UTC, blt commented on lading/src/observer/linux.rs
> +            let cgroup_path = v2::get_path(pid).await?;
Done in [6b05a98](https://github.com/DataDog/lading/pull/1120/commits/6b05a985853eec8adee2b0af4eced9dec959b569).

2024-12-03 23:11 UTC, blt commented on lading/src/observer/linux.rs
> -                let working_set = if usage < inactive_file {
Oh hmm. So in the new cgroup sampler we never actually inspect any of the data being read, just immediately rip it out to metrics. I think we could calculate this easily enough in-platform or we could make a special read to preserve this. 

Happy to move forward with either, but you're right. `working_set` won't be present in the new telemetry stream.

2024-12-04 19:57 UTC, scottopell commented on lading/src/observer/linux/cgroup/v2.rs
> +                                        Some(s) => format!("cgroup.v2.{s}"),
Annotating for my own comprehension, this will be eg `cgroup.v2.memory.stat`

2024-12-04 19:57 UTC, scottopell commented on lading/src/observer/linux/cgroup/v2.rs
> +                                            // Skip files with non-UTF-8 names
worth a `warn` here? I would be pretty shocked if there were any cgroup file names that were not valid utf-8

2024-12-04 19:57 UTC, scottopell commented on lading/src/observer/linux/cgroup/v2.rs
> +                                            // Cgroup files that have values are either single-valued or
I went looking for the rules for these files and found this
https://docs.kernel.org/admin-guide/cgroup-v2.html#interface-files

It looks like multiple values aren't supported (whether new-line separated or space separated) and nested keyed aren't supported.

Worth refactoring this `match` to ... match the documented potential options, even if we intentionally don't support some of them.

2024-12-04 19:57 UTC, scottopell commented on lading/src/observer/linux/cgroup/v2.rs
> +                                    match fs::read_to_string(&file_path).await {
Worth checking if the file is readable up-front, some entries in cgroupv2 are write-only. eg:
```
--w-------  1 root root 0 Jul 15 21:02 memory.reclaim
-r--r--r--  1 root root 0 Jul 15 21:02 memory.stat
```

2024-12-04 19:57 UTC, scottopell commented on lading/src/observer/linux/procfs.rs
> +/// Sampler implementation for procfs filesystems
Any changes to review here? looks like its purely a refactor

2024-12-05 15:36 UTC, scottopell commented on lading/src/observer/linux.rs
> -                let working_set = if usage < inactive_file {
I'd be interested in preserving it, calculating it in-platform is possible, but has zero-discoverability.

Since our intention is to mimic k8s's `working_set`, lets name it `k8s-like.working_set` or something like that.

2024-12-05 17:40 UTC, blt commented on lading/src/observer/linux/cgroup/v2.rs
> +                                        Some(s) => format!("cgroup.v2.{s}"),
Exactly.

2024-12-05 22:20 UTC, blt commented on lading/src/observer/linux.rs
> -                let working_set = if usage < inactive_file {
Ah yeah, I'll add that in a separate PR up-stack. Figure I'll make a k8s reader where we can put any synthetic measures like this.

2024-12-05 22:20 UTC, blt commented on lading/src/observer/linux/procfs.rs
> +/// Sampler implementation for procfs filesystems
Nope, purely mechanical.

2024-12-05 22:56 UTC, blt commented on lading/src/observer/linux/cgroup/v2.rs
> +                                    match fs::read_to_string(&file_path).await {
Ah actually that metadata check is pretty much embedded in the read attempt, so we double up the syscalls by doing a check up front.

2024-12-05 23:01 UTC, blt commented on lading/src/observer/linux/cgroup/v2.rs
> +                                            // Cgroup files that have values are either single-valued or
Will update the documentation.

2024-12-05 23:01 UTC, blt commented on lading/src/observer/linux/cgroup/v2.rs
> +                                            // Skip files with non-UTF-8 names
Addressed in [67078d8](https://github.com/DataDog/lading/pull/1120/commits/67078d87aaf41619b0303d1122020001453e9fbb)

2024-12-05 23:02 UTC, blt commented on lading/src/observer/linux/cgroup/v2.rs
> +                                            // Cgroup files that have values are either single-valued or
Addressed in [67078d8](https://github.com/DataDog/lading/pull/1120/commits/67078d87aaf41619b0303d1122020001453e9fbb)

2024-12-05 23:02 UTC, blt commented on lading/src/observer/linux/cgroup/v2.rs
> +                                    match fs::read_to_string(&file_path).await {
Addressed in [67078d8](https://github.com/DataDog/lading/pull/1120/commits/67078d87aaf41619b0303d1122020001453e9fbb)

2024-12-06 15:38 UTC, scottopell approved these changes
Looks good, thanks for the iterations. My main concern is around treating all cgroup-parsed data as `counts`, but we can iterate on this as we go.

2024-12-06 15:38 UTC, scottopell commented on lading/src/observer/linux/cgroup/v2.rs
> +                                    match fs::read_to_string(&file_path).await {
eh, not going to hold up the PR, but we already fetch the file metadata to determine if its a file. So really you just need to check `if metadata.is_file && metadata.permissions.is_readable` above.

2024-12-06 15:38 UTC, scottopell commented on lading/src/observer/linux/cgroup/v2.rs
> +                gauge!(metric_name, labels).set(value);
Not a blocking concern, but are there any values that should be collected as `count`s rather than gauges? I think they'll reveal themselves shortly if they exist, but I could imagine some of these entries (I'm thinking `memory.events` has `oom_kills` for example) would be counts.

2024-12-06 15:39 UTC, merged

2024-12-06 15:39 UTC, blt commented
### Merge activity

* **Dec 6, 10:39 AM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/DataDog/lading/1120).