Expand smaps / smaps_rollup parsing
DataDog/lading pull request #1130
Opened 2024-12-05 01:45 UTC by blt

### What does this PR do?

This commit expands the number of fields we parse from the smaps/smaps_rollup
files. I have not hooked these up yet to metrics emission but will in a follow-up
commit to this PR.

2024-12-05 01:45 UTC, blt commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/DataDog/lading/1130?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1130** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1130?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/DataDog/lading/1130?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#1129** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1129?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1128** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1128?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1127** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1127?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1124** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1124?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1120** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1120?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1125** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1125?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1126** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1126?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-05 08:13 UTC, GeorgeHahn approved these changes

2024-12-05 08:13 UTC, GeorgeHahn commented on lading/src/observer/linux/procfs/memory/smaps.rs
> +            locked: locked.unwrap_or(0),
Some preference towards doing the same thing with `size, pss, rss, and swap` to make handling consistent unless there's a reason to have different behavior for those.

2024-12-05 18:19 UTC, scottopell requested changes

2024-12-05 18:19 UTC, scottopell commented on lading/src/observer/linux/procfs/memory/smaps.rs
> +            locked: locked.unwrap_or(0),
Agreed, I'd like to see the required fields unwrapped similarly to how `size, pss, rss` etc are unwrapped above. 
Only a few of these fields are actually optional, and I don't want to report `0` incorrectly.

2024-12-05 23:14 UTC, blt commented on lading/src/observer/linux/procfs/memory/smaps.rs
> +            locked: locked.unwrap_or(0),
Hmm the more I look at this the more I think the current approach is bankrupt. Best to read the whole file in, rip through it and create metrics without the intermediary structure.

2024-12-06 15:52 UTC, scottopell commented on lading/src/observer/linux/procfs/memory/smaps.rs
> +            locked: locked.unwrap_or(0),
new approach seems good in terms of simpler code, but I'm concerned that we're blindly reporting 0 for any values that don't exist. 
Unless I'm misunderstanding the code here, but it seems like we would end up reporting `0` in cases where there is no value, which makes this data confusing to work with.

2024-12-06 19:23 UTC, scottopell approved these changes

2024-12-06 19:23 UTC, merged

2024-12-06 19:23 UTC, blt commented
### Merge activity

* **Dec 6, 2:23 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/DataDog/lading/1130).