Instrument connection limit and current count for http blackholes
DataDog/lading pull request #1190
Opened 2024-12-30 18:44 UTC by blt

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

2024-12-30 18:44 UTC, blt commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/DataDog/lading/1190?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1190** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1190?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/DataDog/lading/1190?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#1187** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1187?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1186** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1186?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1182** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1182?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1181** <a href="https://app.graphite.dev/github/pr/DataDog/lading/1181?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-30 18:50 UTC, blt commented
CC @remeh

2024-12-30 19:04 UTC, scottopell requested changes

2024-12-30 19:04 UTC, scottopell commented on lading/src/blackhole/common.rs
> +        gauge!("connection.current", &labels).set(sem.available_permits() as f64);
we claim a permit upon accepting a connection, so wouldn't `available_permits` be the inverse of what we want? ie, we should use `sem.claimed_permits` to track the number of current connections

2024-12-30 19:31 UTC, blt commented on lading/src/blackhole/common.rs
> +        gauge!("connection.current", &labels).set(sem.available_permits() as f64);
D'oh, yep.

2024-12-30 19:34 UTC, blt commented on lading/src/blackhole/common.rs
> +        gauge!("connection.current", &labels).set(sem.available_permits() as f64);
[75ecd70](https://github.com/DataDog/lading/pull/1190/commits/75ecd704ec8bb8725994d1f2476e681eab63902b)

2024-12-31 17:34 UTC, scottopell approved these changes

2024-12-31 17:35 UTC, merged

2024-12-31 17:35 UTC, blt commented
### Merge activity

* **Dec 31, 12:35 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/DataDog/lading/1190).