add a file tree generator
DataDog/lading pull request #356
Opened 2022-10-19 12:40 UTC by safchain

Signed-off-by: Sylvain Afchain <sylvain.afchain@datadoghq.com>

### What does this PR do?

Add a file tree generator. First the generator generates a tree, then it randomly generates file access and folder rename.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

2022-10-19 15:57 UTC, paulcacheux commented on src/generator/file_tree.rs
> +    node
```suggestion
    let name = Alphanumeric.sample_string(rng, len);
    dir.join(name)
```

2022-10-19 16:14 UTC, GeorgeHahn requested changes
This is looking great! There's one change I'd like to ask for. We try to do as much work as possible at startup to keep generators fast at runtime. Could you switch the node name generation to create a large list at startup and pull from that as needed?

2022-10-20 11:42 UTC, safchain commented on src/generator/file_tree.rs
> +    node
Done, thanks

2022-10-20 11:43 UTC, safchain commented
@GeorgeHahn thanks for having a look. I submitted a new version, the list of nodes (file/folder) are now generated in the new function.

2022-10-20 16:09 UTC, blt commented on src/generator/file_tree.rs
> +    pub rename_per_second: NonZeroU32,
I wouldn't be mad at some reasonable defaults for these non-zero values, but that we can tidy up in a follow-up.

2022-10-21 15:17 UTC, safchain commented on src/generator/file_tree.rs
> +    pub rename_per_second: NonZeroU32,
I added some default

2022-10-21 15:53 UTC, safchain commented on src/generator/file_tree.rs
> +                            if let Some(node) = files.choose(&mut self.rng) {
I move the file/folder allocations to the `new`  function

2022-10-21 20:38 UTC, blt approved these changes
This is looking great to me. I'll be happy to see it merged.

2022-10-21 20:47 UTC, GeorgeHahn approved these changes
This looks fantastic! Thank you @safchain.

2022-10-21 20:48 UTC, merged