introduce process tree generator
DataDog/lading pull request #424
Opened 2022-12-27 16:04 UTC by safchain

### What does this PR do?

This PR adds a process tree generator. The goal is to generate a process tree with variable width and height. The leaves execute a command line specified in the config file with static args/envs or generated ones. A typical "pstree like" gives : 

```
1994835  437791  |   |   |   |       \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999492 1994835  |   |   |   |           \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999545 1999492  |   |   |   |               \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999914 1999545  |   |   |   |               |   \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999547 1999492  |   |   |   |               \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999915 1999547  |   |   |   |               |   \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999610 1999492  |   |   |   |               \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999917 1999610  |   |   |   |               |   \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999850 1999492  |   |   |   |               \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999916 1999850  |   |   |   |               |   \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999908 1999492  |   |   |   |               \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999918 1999908  |   |   |   |               |   \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
1999919 1999492  |   |   |   |               \_ ./target/debug/lading --config-path ./examples/lading.yaml --target-pid 83568
``` 

In a follow-up PR cgroups handling will be introduce.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

2023-01-03 22:56 UTC, blt requested changes
I have some comments but this is good stuff. If some of the comments about blocking don't make sense I'm happy to pair up.

2023-01-03 22:56 UTC, blt commented on src/generator/process_tree.rs
> +fn spawn_tree(nodes: &VecDeque<Process>, sleep_ns: u32) {
One immediate problem here is that this function needs to be `async`, else the loop beginning on 266 doesn't properly function and the whole of lading might not either. This function is thread blocking and doesn't time share properly, meaning if lading is run on a single core other tasks in lading will be denied access to the CPU, even if `thread::sleep` is the only thing happening. 

`try_wait_pid` uses the nix crate to wait on pids, although I think this generator could be written in terms of [`tokio::process`](https://docs.rs/tokio/latest/tokio/process/) and avoid the blocking nature. If there's some nuance I'm missing, possibly around cgroup addition, then calling [`spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) with `spawn_tree` would be the right move.

2023-01-03 22:56 UTC, blt commented on src/generator/process_tree.rs
> +    pub mode: String,
Please convert this to an enum. You'd have in this module:

```rust
enum Mode {
  Static,
  Generate
}
```

and then below when you do string comparisons you can instead check for the enum variant, much cheaper and type-safe.

2023-01-03 22:56 UTC, blt commented on src/generator/process_tree.rs
> +            exit(status.code().unwrap())
This `exit` will kill the whole of lading. Other sinks have a careful shut-down process and we exit only for catastrophic errors. It's not clear to me why we need to exit with the child's status here?

2023-01-03 22:56 UTC, blt commented on src/generator/process_tree.rs
> +    }
Considering that this is called not infrequently it would be better to add an `is_exec` boolean in the struct. Also, under what conditions does a `Process` exist but not have an executable? @GeorgeHahn is better with clap than me but if the concern is config validation we can ensure the user can't set an empty string here.

2023-01-04 03:17 UTC, GeorgeHahn requested changes
Thanks for the PR! This is going in a good direction. My main concern is around the `fork` at the core of the tree generator. Extracting that should also address the comments Brian raised around async & child shutdown.

2023-01-05 14:38 UTC, safchain commented on src/generator/process_tree.rs
> +fn spawn_tree(nodes: &VecDeque<Process>, sleep_ns: u32) {
Thanks @blt I'll convert it to an async version.

2023-01-05 14:43 UTC, safchain commented on src/generator/process_tree.rs
> +            exit(status.code().unwrap())
Since we are in the is_exec case it means we are in the child(leaf) process. In this child process we exec(fork/exec) and then we exit. I don't think it exit the whole lading process(main). At least this is not what I observed when I developed it but I could have miss something.

2023-01-05 14:46 UTC, safchain commented
@blt , @GeorgeHahn thanks for the review, that is really useful. I'll work on addressing your comments.

2023-01-05 15:08 UTC, safchain commented on src/generator/process_tree.rs
> +    }
Good point. I'll add a boolean and add a check to ensure that the path is an executable

2023-01-05 16:33 UTC, blt commented on src/generator/process_tree.rs
> +            exit(status.code().unwrap())
On further examination I was confused and I believe you are correct.

2023-01-18 12:44 UTC, safchain commented
@blt @GeorgeHahn I updated the PR. I tried to address your comments. Now the process generator is made of a hidden  subcommand.

2023-01-23 19:06 UTC, GeorgeHahn reviewed
This is looking great!

2023-01-23 19:06 UTC, GeorgeHahn commented on src/generator/process_tree.rs
> +                        .spawn();
This should emit a log message or return an error if spawn fails

2023-01-23 20:24 UTC, blt approved these changes
This looks great to me. I had one small comment but I'd be glad to see this go in as-is.

2023-01-23 20:24 UTC, blt commented on src/generator/process_tree.rs
> +    pub process_sleep_ns: NonZeroU32,
This could be a [`Duration`](https://doc.rust-lang.org/std/time/struct.Duration.html) directly. Not strictly necessary, more of a comment.

2023-01-23 20:24 UTC, blt commented on src/generator/process_tree.rs
> +                        .spawn();
+1, I think an error so we can shutdown quickly.

2023-01-23 20:24 UTC, blt commented on src/generator/process_tree.rs
> +        match unsafe { fork() } {
@GeorgeHahn I think this is resolved?

2023-01-24 13:30 UTC, safchain commented on src/bin/lading.rs
> +        ExtraCommands::ProcessTreeGen(opts) => run_process_tree(opts),
Done

2023-01-24 13:30 UTC, safchain commented on src/generator/process_tree.rs
> +    pub process_sleep_ns: NonZeroU32,
I would like to do it but it will make the configuration parsing a bit more complex to parse the Duration

2023-01-24 15:17 UTC, safchain commented on src/generator/process_tree.rs
> +                        .spawn();
Done

2023-01-24 22:17 UTC, GeorgeHahn commented on src/generator/process_tree.rs
> +                        .arg("--config-contdqdsent")
Accidental addition here

2023-01-25 09:24 UTC, safchain commented on src/generator/process_tree.rs
> +                        .arg("--config-contdqdsent")
oups, thanks, fixed

2023-01-25 18:14 UTC, GeorgeHahn approved these changes

2023-01-25 18:39 UTC, merged