Waits on generator's execution in order to print out any errors
DataDog/lading pull request #759
Opened 2023-12-04 18:20 UTC by scottopell

### What does this PR do?
Adds logic in the main `select` loop of `lading` to wait for the result of the generators that were spawned.

### Motivation
While there is good error handling inside the generators that give feedback when an invalid condition is hit, that result was not being read anywhere.

### Related issues

### Additional Notes

2023-12-04 18:26 UTC, scottopell commented
This is a slightly different pattern from the other "waitables" here, for example the blackholes spawn an async task in-line that blocks on the results, rather than wait in the central `select`.

Is there any significant advantage to one vs the other? The `future::select_all` seems preferable to me with the goal of having fewer tasks, but I'm not too familiar with tokio and if this is a valid consideration.

2023-12-04 20:42 UTC, blt requested changes

2023-12-04 20:42 UTC, blt commented on lading/src/bin/lading.rs
> +        gsrv_handles.push(_gsrv);
As a matter of convention this should be changed to `gsrv` here and the line prior.

2023-12-04 20:42 UTC, blt commented on lading/src/bin/lading.rs
> +    let gsrv_waitable = futures::future::select_all(gsrv_handles);
I'd prefer the use of a [`JoinSet`](https://docs.rs/tokio/latest/tokio/task/struct.JoinSet.html). While I think this will work keeping all our uses to tokio avoids historical performance stutters caused by different assumptions between futures/tokio and means upgrades to the crates come for free.

2023-12-04 20:42 UTC, blt commented on lading/src/bin/lading.rs
> +        }
Neat.

2023-12-04 20:44 UTC, blt commented
> This is a slightly different pattern from the other "waitables" here, for example the blackholes spawn an async task in-line that blocks on the results, rather than wait in the central `select`.
> 
> Is there any significant advantage to one vs the other? The `future::select_all` seems preferable to me with the goal of having fewer tasks, but I'm not too familiar with tokio and if this is a valid consideration.

The major difference is that if there is a failure in the blackhole the main task will not be aware of it. This is probably not the best construction. We may also, now that I'm thinking about it, want to bubble the generator error up in an error return, shutting the program down.

2023-12-04 22:16 UTC, scottopell commented on lading/src/bin/lading.rs
> +    let gsrv_waitable = futures::future::select_all(gsrv_handles);
Thanks! I didn't run across `JoinSet`, it seems like a better fit given that these handles are all already `JoinHandles`.

2023-12-04 22:19 UTC, scottopell commented
> The major difference is that if there is a failure in the blackhole the main task will not be aware of it. This is probably not the best construction. We may also, now that I'm thinking about it, want to bubble the generator error up in an error return, shutting the program down.

Would probably be a good future pass through this logic, to ensure that errors in any subcomponent shut down the program (rather than simply log an error as the current implementation does).

2023-12-05 00:49 UTC, blt commented
> > The major difference is that if there is a failure in the blackhole the main task will not be aware of it. This is probably not the best construction. We may also, now that I'm thinking about it, want to bubble the generator error up in an error return, shutting the program down.
> 
> Would probably be a good future pass through this logic, to ensure that errors in any subcomponent shut down the program (rather than simply log an error as the current implementation does).

Strong agree.

2023-12-05 14:27 UTC, merged