Removing More Expects
DataDog/lading pull request #802
Opened 2024-02-02 22:38 UTC by dmalis18

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Related issues

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

2024-02-03 00:20 UTC, blt commented
> ### What does this PR do?
> A brief description of the change being made with this pull request.
> 
> ### Motivation
> What inspired you to submit this pull request?
> 
> ### Related issues
> A list of issues either fixed, containing architectural discussions, otherwise relevant for this Pull Request.
> 
> ### Additional Notes
> Anything else we should know when reviewing?

Do fill this out please. It's important for understanding the purpose of the PR and keeping track of what work it maps to.

2024-02-03 00:25 UTC, blt requested changes

2024-02-03 00:25 UTC, blt commented on lading/src/generator/splunk_hec.rs
> +    Next,
This leaks internal implementation details and is not helpful to a user. Better to have something that is like "Attempted to iterate a closed iterator" if we want to keep the language specific to iterators. That said, I'm unsure that the _iterator_ is central to communicate here so much as we've run out of channels.

2024-02-03 00:25 UTC, blt commented on lading/src/generator/splunk_hec.rs
> +    Next,
We might also consider this an example of `except` not being all bad. Neither of these conditions should happen -- that is, we lack a SAFETY comment. Personally I'd vote to leave the excepts and not have the errors. They can't be handled anyway as these errors are catastrophic programming mistakes if they fire.

2024-02-03 00:25 UTC, blt commented on lading/src/generator/splunk_hec.rs
> +    Next,
Same comment for repeats of this pattern.

2024-02-03 02:57 UTC, dmalis18 commented on lading/src/generator/splunk_hec.rs
> +    Next,
That logic makes sense. I'll go back and reset them back to expects on Monday since it is more useful given the SAFETY issues if it fails.

2024-02-05 21:54 UTC, blt commented on lading/src/generator/file_gen/logrotate.rs
> +                    let blk = rcv.next().await.expect("there is no next block in rcv"); // actually advance through the blocks
I think the original language here was fine, but I'd be curious to know what you're attempting to communicate with the adjustment. My basic concern is "rcv" is the name of an internal variable and doesn't necessarily communicate anything to the end user that does not require internal knowledge of the program.

2024-02-05 22:00 UTC, dmalis18 commented on lading/src/generator/file_gen/logrotate.rs
> +                    let blk = rcv.next().await.expect("there is no next block in rcv"); // actually advance through the blocks
I did not realize that the rcv.nexts had different error messages when I originally made them to expect so I just took a standard message from one of them and placed it in all the spots that I had added the error types for it

2024-02-05 22:01 UTC, dmalis18 commented on lading/src/generator/file_gen/logrotate.rs
> +                    let blk = rcv.next().await.expect("there is no next block in rcv"); // actually advance through the blocks
Seems like a lot of these had unintentionally different expect messages

2024-02-05 22:02 UTC, dmalis18 commented on lading/src/generator/file_gen/logrotate.rs
> +                    let blk = rcv.next().await.expect("there is no next block in rcv"); // actually advance through the blocks
I am gonna back through and revert the changes to be more informative about the error and not about the internal details.

2024-02-05 22:20 UTC, blt approved these changes

2024-02-06 15:16 UTC, merged