Enable tagging of target metrics from prometheus and expvar endpoints by sub-agent name
DataDog/lading pull request #941
Opened 2024-08-16 13:45 UTC by cmetz100

…r endpoint

### What does this PR do?

This PR adds another configuration option to prometheus and expvar target metrics enabling a user to tag all the metrics coming from that configuration with a sub agent label

### Motivation

Currently in lading we could configure several prometheus endpoints to listen on to collect target metrics. In the case of the agent being the target we could configure separate prometheus target metrics to get the internal telemetry of different sub agents. This issue is that when we do this there are some duplicate metrics across the sub agents. For example both the core agent and process agent expose workloadmeta telemetry. We want a way to differentiate not just the duplicate metrics but all of them, so that we can investigate the performance of each sub-agent on its own.

### Related issues

[SMPTNG-422](https://datadoghq.atlassian.net/browse/SMPTNG-422)

A list of issues either fixed, containing architectural discussions, otherwise relevant
for this Pull Request.

### Additional Notes

Anything else we should know when reviewing?

2024-08-16 13:51 UTC, scottopell requested changes
I like the overall approach, lets change the `sub_agent` terminology to be something more generic. `lading` is intended to be "target agnostic", so the target could be the Datadog Agent, but it could also be Vector or any other arbitrary program.

It also appears that there may be missing files from this branch, I would guess there are changes incoming in `target_metrics/expvar.rs` as well as `lading.rs`

2024-08-16 13:51 UTC, scottopell commented on lading/src/target_metrics/prometheus.rs
> +    async fn run_scrape_and_parse_metrics_with_sub_agent_label(
it appears that this is very similar to the above `run_scrape_and_parse_metrics`, is there a good way to combine these to avoid duplicating this code?

2024-08-16 14:09 UTC, cmetz100 commented
> I like the overall approach, lets change the `sub_agent` terminology to be something more generic. `lading` is intended to be "target agnostic", so the target could be the Datadog Agent, but it could also be Vector or any other arbitrary program.
> 
> It also appears that there may be missing files from this branch, I would guess there are changes incoming in `target_metrics/expvar.rs` as well as `lading.rs`

I was thinking about expanding the functionality once i got this working to enable the addition of a arbitrary amount of key value labels so that we could configure appropriate label names for whatever target. And yeah working on the expvar changes right now.

2024-08-16 14:12 UTC, cmetz100 commented on lading/src/target_metrics/prometheus.rs
> +    async fn run_scrape_and_parse_metrics_with_sub_agent_label(
I could refactor the tests to have the prometheus configuration passed in from the test function rather than being defined in the scraping helpers yeah. Going to do this after I refactor to generalize labels to any target

2024-08-19 15:28 UTC, scottopell approved these changes

2024-08-20 15:50 UTC, scottopell commented on CHANGELOG.md
> +          sub-agent: "core-agent"
```suggestion
          sub_agent: "core"
```

small suggestion here to prefer `_` instead of `-` for consistence with our other metrics (eg, `job_id`) and to not duplicate the word "agent" in the value

2024-08-20 17:19 UTC, cmetz100 commented on CHANGELOG.md
> +          sub-agent: "core-agent"
makes sense to me

2024-08-20 17:20 UTC, cmetz100 commented on CHANGELOG.md
> +          sub-agent: "core-agent"
these changes really apply for the changes I will make in [this pr](https://github.com/DataDog/single-machine-performance/pull/2069) but I can update the examples here accordingly

2024-08-29 14:37 UTC, merged